language: csharp
solution: MicroIOC.sln
install:
  - nuget restore MicroIOC.sln
  - nuget install nunit-console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MicroIOC.sln
  - nunit-console ./MicroIOC/bin/Release/MicroIOC.Test.dll
