language: csharp
solution: MicroIOC.sln
install:
  - nuget restore MicroIOC.sln
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Release MicroIOC.sln
  after_script:
  - nunit-console ./MicroIOC/bin/Release/MicroIOC.Test.dll
