language: csharp
solution: MicroIOC.sln
install:
  - nuget restore MicroIOC.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MicroIOC.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MicroIOC/bin/Release/MicroIOC.Test.dll